name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint php
        uses: 10up/wpcs-action@develop
        with:
          standard: Wordpress-Core
          use_local_config: "true"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: Lint npm
        run: |
          npm run lint:js
          npm run lint:css

      - name: Build/test
        run: |
          npm run build

  tag:
    runs-on: ubuntu-latest
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Git config
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Bump version
        id: version
        shell: bash
        run: |
          MSG=$(git log -1 --pretty=%B)
          if [[ "$MSG" == "<bot>" ]]; then
            echo "already tagged"
            exit 1
          fi
          cat <<EOF >/tmp/bump_version.py
          import json, logging
          logging.basicConfig(level=logging.DEBUG)
          data = json.load(open('package.json'))
          old_version = [int(v) for v in data['version'].split('.')]
          logging.info('old version: %r', old_version)
          commit_msg = """${MSG}"""
          logging.info('last commmit message: %s', commit_msg)
          if commit_msg.startswith('[major]'):
            version = (old_version[0]+1, 0, 0)
          elif commit_msg.startswith('[minor]'):
            version = (old_version[0], old_version[1]+1, 0)
          else:
            version = (old_version[0], old_version[1], old_version[2]+1)
          logging.info('new version: %r', version)
          version_str = '.'.join(str(v) for v in version)
          data['version'] = version_str
          json.dump(data, open('package.json','w'), indent=4)
          php_data = []
          with open('wordpress-gen2-plugin.php') as f:
            for line in f.readlines():
              if 'Version:' in line:
                line = ' * Version: '+version_str
              php_data.append(line.rstrip())
          open('wordpress-gen2-plugin.php','w').write('\n'.join(php_data))
          print(version_str)
          EOF
          VERSION=$(python /tmp/bump_version.py)
          git add package.json wordpress-gen2-plugin.php
          git commit -m "<bot> update version"
          git push
          SHA=$(git rev-parse HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          commit_sha: ${{ steps.version.outputs.sha }}
          # uncomment if running actions on tags
          #github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: Create artifact
        run: |
          npm run build
          npm run plugin-zip

      - name: Create release for tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: |
            @${{ github.repository }}.zip
